universe = vanilla
executable = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/run_batch.sh
initialdir = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908/cards
arguments = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908/cards/collect_$(topology).argv
output = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908/logs/collect.$(ClusterId).$(ProcId).out
error = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908/logs/collect.$(ClusterId).$(ProcId).err
log = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908/logs/collect.$(ClusterId).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_executable = TRUE
transfer_input_files = /eos/user/t/taiwoo/run3_stop/runtime/py38.tgz
transfer_output_files = ""
getenv = False
environment = "BATCH_RUNTIME=py38"
use_x509userproxy = true
x509userproxy = /eos/user/t/taiwoo/decaf/analysis/proxy/x509up_u147757
request_cpus = 1
request_memory = 3000MB
request_disk = 4000MB
+JobFlavour = "workday"
+MaxRuntime = 28800
+JobBatchName = "NPS26012_TopW_limit_collection"
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
queue topology from (
T2tt
T2bW
T2tb
)
