universe = vanilla
initialdir = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/reports/background_estimation_lepton_veto10_20260908
executable = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/reports/background_estimation_lepton_veto10_20260908/batch/run_batch.sh
arguments = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/reports/background_estimation_lepton_veto10_20260908/batch/$(year).argv
getenv = False
output = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/reports/background_estimation_lepton_veto10_20260908/batch/logs/calculation_$(year).$(ClusterId).out
error = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/reports/background_estimation_lepton_veto10_20260908/batch/logs/calculation_$(year).$(ClusterId).err
log = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/reports/background_estimation_lepton_veto10_20260908/batch/logs/calculation.$(ClusterId).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_executable = TRUE
transfer_input_files = /eos/user/t/taiwoo/run3_stop/runtime/py38.tgz
transfer_output_files = ""
use_x509userproxy = true
x509userproxy = /eos/user/t/taiwoo/decaf/analysis/proxy/x509up_u147757
request_cpus = 1
request_memory = 6000MB
request_disk = 5000MB
+MaxRuntime = 7200
+JobBatchName = "NPS26012_BackgroundVeto10_calculation"
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
queue year in 2024, 2025
