universe = vanilla

executable = /eos/user/t/taiwoo/run3_stop/decaf/analysis/condor/run_condor_2024.sh
arguments  = $(dataset) $(shift)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_executable = TRUE

# inputs: tarballs + proxy
transfer_input_files = \
  /eos/user/t/taiwoo/run3_stop/decaf/condor/analysis.tgz, \
  /eos/user/t/taiwoo/run3_stop/decaf/condor/py38.tgz, \
  /eos/user/t/taiwoo/run3_stop/decaf/analysis/proxy/x509up_u147757

# run_condor_2024.sh creates this file in scratch
transfer_output_files = out.futures

# Send output directly to the final shift directory
transfer_output_remaps = "out.futures=/eos/user/t/taiwoo/run3_stop/decaf/analysis/hists/stop_2024_$(shift)/$(dataset).futures"

# Condor logs
executable = /eos/user/t/taiwoo/run3_stop/decaf/condor/run_condor_2024.sh

# One shared log file for the entire cluster
output = job.$(ClusterId).log
error  = job.$(ClusterId).log
log    = job.$(ClusterId).log

request_cpus   = 1
request_memory = 6000
request_disk   = 12000

use_x509userproxy = true
getenv = true
+JobFlavour = "workday"


# JER up
shift = jerUp
queue dataset from /eos/user/t/taiwoo/run3_stop/decaf/analysis/datasets/datasets_2024_onlymc.txt


# JER down
shift = jerDown
queue dataset from /eos/user/t/taiwoo/run3_stop/decaf/analysis/datasets/datasets_2024_onlymc.txt