universe = vanilla
initialdir = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/systematic_propagation/full_met_20260911/2025
executable = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/systematic_propagation/run.sh
arguments = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/systematic_propagation/run.py worker --config $(config) --shift $(shift) --output $(resultdir)
getenv = False
output = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/systematic_propagation/full_met_20260911/2025/logs/$(shard)_$(shift).$(ClusterId).out
error = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/systematic_propagation/full_met_20260911/2025/logs/$(shard)_$(shift).$(ClusterId).err
log = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/systematic_propagation/full_met_20260911/2025/logs/jobs.$(ClusterId).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_executable = True
transfer_input_files = /eos/user/t/taiwoo/run3_stop/runtime/py38.tgz, /eos/user/t/taiwoo/run3_stop/runtime/mt2-1.2.0-cp38-cp38-manylinux2010_x86_64.whl
transfer_output_files = ""
use_x509userproxy = True
x509userproxy = /eos/user/t/taiwoo/decaf/analysis/proxy/x509up_u147757
request_cpus = 2
request_memory = $(memory)
request_disk = 25000MB
+JobFlavour = "workday"
+MaxRuntime = 28800
+JobBatchName = "NPS26012_shape_full_met_20260911_2025"
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
queue shard,shift,config,resultdir,memory from /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/systematic_propagation/full_met_20260911/2025/jobs.queue
