universe = vanilla
initialdir = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908
executable = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/run_batch.sh
arguments = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908/$(year)/gnn_merge.argv
getenv = False
environment = "PYTHONPATH=/eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908/gnn_code/autonomous_allhad LOWDM_TEST_REPOSITORY_OVERRIDE=/eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908/gnn_code AUTONOMOUS_ALLHAD_LOCAL_ANALYSIS_DATA=0"
output = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908/logs/gnn_merge_$(year).$(ClusterId).out
error = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908/logs/gnn_merge_$(year).$(ClusterId).err
log = /eos/user/t/taiwoo/run3_stop/decaf/autonomous_allhad/workflow/histograms/lepton_veto10_20260908/logs/gnn_merge.$(ClusterId).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_executable = TRUE
transfer_input_files = /eos/user/t/taiwoo/run3_stop/runtime/py38.tgz, /eos/user/t/taiwoo/run3_stop/runtime/mt2-1.2.0-cp38-cp38-manylinux2010_x86_64.whl
transfer_output_files = ""
use_x509userproxy = true
x509userproxy = /eos/user/t/taiwoo/decaf/analysis/proxy/x509up_u147757
request_cpus = 1
request_memory = 32000MB
request_disk = 6000MB
+MaxRuntime = 28800
+JobFlavour = "workday"
+JobBatchName = "NPS26012_LeptonVeto10_GNN_merge"
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
merge_years = 2024, 2025
queue year in $(merge_years)
